---
#
# Ansible managed
#
repository:
  description: Create partitions, volume groups, volumes, filesystems and mounts
  homepage: https://buluma.github.io/
  topics: storage, system, ansible, molecule, playbook
